---
title: "Regular Expression Puzzles"
author: "Emma Gagne"
date: "2/9/2021"
output: html_document
---

# Problem 1

We started with this;

```
First String    Second      1.22        3.4
Second          More Text   1.555555    2.2220
Third           x           3           124
```

And transformed it to this;
```
First String,Second,1.22,3.4
Second,More Text,1.555555,2.2220
Third,x,3,124
```
This is what I typed into the find and replace;  
Find: `\t+`  
This is telling BBEdit to find all the places were one or more tabs exists.

Replace: `\, `  
This is telling BBEdit to replace every place where there are one or more tabs with just a comma and a space.

**This is useful when converting an Excel spreadsheet into what is needed for a proper .csv file**

# Problem 2

We started with this; 
```
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr
```

And transformed it to this;
```
Bryan Ballif (University of Vermont)
Aaron Ellison (Harvard Forest)
Sydne Record (Bryn Mawr)
```

This is what I typed into the find and replace;

Find: `(\w+)\,\s(\w+)\,\s(.*)`  
This is telling BBEdit to find all the places where there is a word, followed by a comma, followed by a space, followed by another word, another comma, and another space, and then all the rest. The parentheses are "captures," which isolate certain characters from the others.  

Replace: `\2 \1 \(\3\)`  
This is telling BBEdit to replace each line with the second capture, a space, the first capture, a space, and then all the rest of the line in parentheses.

# Problem 3

We started with this; 
```
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3
```

And transformed it to this;
```
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Cherokee Shuffle.mp3
0004 Walking Cane.mp3
```

This is what I typed into the find and replace;

Find: `(\w{4}\s\w+\s\w+\s*\w*\s*\w*\.mp3)(\s*)`

This is telling BBEdit to find every mp3 file in the line.  

Replace: `\1\n`

This is telling BBEdit to take the mp3 files and create a new line after each one.

# Problem 4

We started with this; 
```
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Cherokee Shuffle.mp3
0004 Walking Cane.mp3
```

And transformed it to this;
```
Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Cherokee Shuffle_0003.mp3
Walking Cane_0004.mp3
```

This is what I typed into the find and replace;

Find: `(\w{4})\s(\w+\s\w+\s*\w*\s*\w*)(\.mp3)`

This is telling BBEdit to find every mp3 file in each line. I captured the names of the song, the four digit number, and the .mp3 seperately.  

Replace: `\2_\1\3`  
This tells BBEdit how to reformat and rearrange each captured region appropriately.

# Problem 5

We started with this; 
```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55
```

And transformed it to this;
```
C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55
```

This is what I typed into the find and replace;

Find: `(\w)\w+\,(\w+)\,\d+\.\d+\,(\d+)`

This tells BBEdit to capture the first letter of the first word, the second word, and the second number set.   

Replace: `\1_\2,\3`  
This tells BBEdit how to reformat and rearrange each captured region appropriately.

# Problem 6

We started with this; 
```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55
```

And transformed it to this;
```
C_penn,44
C_herc,3
M_punc,4
L_neon,55
```

This is what I typed into the find and replace;

Find: `(\w)\w+\,(\w{4})\w+\,\d+\.\d+\,(\d+)`

This tells BBEdit to capture the first letter of the first word, the first four letters of the second word, and the second number set.   

Replace: `\1_\2,\3`  
This tells BBEdit how to reformat and rearrange each captured region appropriately.

# Problem 7

We started with this; 
```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55
```

And transformed it to this;
```
Campen, 44, 10.2
Camher, 3, 10.5
Myrpun, 4, 12.2
Lasneo, 55, 3.3
```

This is what I typed into the find and replace;

Find: `(\w{3})\w+\,(\w{3})\w+\,(\d+\.\d+)\,(\d+)`

This tells BBEdit to capture the first three letters of the first word, the first three letters of the second word, and each number set.   

Replace: `\1\2, \4, \3`  
This tells BBEdit how to fuse the first three letters of the first and second word, and reverse the order of the numberical data.